### PR TITLE
Update to next-mdx-remote v3.

### PR DESCRIPTION
**Pull request by leerob**
https://github.com/hashicorp/next-mdx-remote/pull/121

### CODE REVIEW

**Comment by leerob** [comment]
Prod: `view-source:https://leerob.io/blog/how-stripe-designs-beautiful-websites`
PR: `view-source:https://leerob-git-mdx-remote-v3-leerob1.vercel.app/blog/how-stripe-designs-beautiful-websites`

Looking good!

**Comment by BRKalow** [comment]
Amazing ❤️

If you want to reduce some boilerplate, you can wrap your entire app in an `MDXProvider` and make custom components available that way: https://www.npmjs.com/package/next-mdx-remote/v/3.0.0-alpha.0#mdx-provider

```jsx
// pages/_app.jsx
  
import '@/styles/global.css';

import { ThemeProvider } from 'next-themes';
import { MDXProvider } from '@mdx-js/react';
import MDXComponents from '@/components/MDXComponents';
import { useAnalytics } from '@/lib/analytics';

export default function App({ Component, pageProps }) {
  useAnalytics();

  return (
    <ThemeProvider attribute="class">
      <MDXProvider components={MDXComponents}>
        <Component {...pageProps} />
      </MDXProvider>
    </ThemeProvider>
  );
}
```

**Comment by leerob** [comment]
#### 📝Changed routes:


| [**/blog/\[slug\]**](https://leerob-qfzuo93zr-leerob1.vercel.app/blog/[slug]) | [**/newsletter/\[slug\]**](https://leerob-qfzuo93zr-leerob1.vercel.app/newsletter/[slug]) |
|:-:|:-:|
|<a href="https://leerob-qfzuo93zr-leerob1.vercel.app/blog/[slug]">Screenshot of /blog/[slug]</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/3lzcZZyxh7bGqbYTa3d8KqujIrE_OvuMlWz5ih7XYQwA-Y7A9MyUP0Y0XiD3VQ52v3rxKTwRXUI-KahOcUWopQ.png">(view full size)</a> |<a href="https://leerob-qfzuo93zr-leerob1.vercel.app/newsletter/[slug]">Screenshot of /newsletter/[slug]</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/K9SJvFUKuVao3D4NcaKL9FS0r6SIA5E_dICb-0UUQ9sqQeqbnNVVfYZvX54OzLjEd-GKIOGRt9rbPReMt1veNQ.png">(view full size)</a> |



| [**/snippets/\[slug\]**](https://leerob-qfzuo93zr-leerob1.vercel.app/snippets/[slug]) | [**/uses**](https://leerob-qfzuo93zr-leerob1.vercel.app/uses) |
|:-:|:-:|
|<a href="https://leerob-qfzuo93zr-leerob1.vercel.app/snippets/[slug]">Screenshot of /snippets/[slug]</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/sqkvXWv_KtSy4G33sAzBbJUPIcMXWvCv93BjPis_kSKYzHAq0I710Go-XlytlGn1jJ5ewy1jPlWzMvLtsbdPLA.png">(view full size)</a> |<a href="https://leerob-qfzuo93zr-leerob1.vercel.app/uses">Screenshot of /uses</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/uq8thBH6e4LvxUVrYdM0WVrk7UNKZH22OBzsJJzsWK3ba9soYRMk73f2FMYG0oNFn5X7O5YgHwVmvh0SerkhLw.png">(view full size)</a> |







Commit d368fe8fa5d20270b33beb25310cdb9bc26ae5ae (https://leerob-qfzuo93zr-leerob1.vercel.app).

**Comment by leerob** [comment]
Going for the YOLO merge even though it's still in alpha... what could go wrong?

**Pull request merged**
