### PR TITLE
use layout animation instead of hardcode x, y, width value

### PR DESCRIPTION
**Pull request by malburo**
hi Lee, i just took a look at your sidebar components and saw that we should use framer motion layout animation instead of using x, y, width.

### CODE REVIEW

**Comment by leerob** [comment]
How does this work?

**Comment by malburo** [comment]
- In this case, I created a `motion.div` tag with the attribute `abslute inset-0` to be able to inherit the height and width of the original text, and assigned them `layoutId` in the same `LayoutGroup` namespace

- They all share a common `layoutId` that tells Framer Motion that these components are related and need to transition from one instance to the new "active" version when the user clicks on a new navigation item.

- Framer motion documentation about [layout group](https://www.framer.com/motion/layout-animations/#shared-layout-animations)

**Comment by leerob** [comment]
Wow, this is really cool! Appreciate the details.

**Comment by malburo** [comment]
Thanks Lee. I just learned about framer motion recently, this is so cool!!, gives me a different perspective on animations😁

**Review by leerob — APPROVED** [review]

**Pull request merged**
