### PR TITLE
Next.js 10 + Tailwind CSS

### PR DESCRIPTION
**Pull request by leerob**
Replaces https://github.com/leerob/leerob.io/pull/238.

### CODE REVIEW

**Comment by leerob** [comment]
Waiting for https://github.com/hashicorp/next-mdx-remote/pull/35! 🔥

**Comment by AkashRajpurohit** [comment]
Also since its been some time, Chakra has released v1 completely (which in my PR was release candidate 5). So you can upgrade it to v1 along with framer motion as well (mentioned in their docs) 😄 @leerob

**Comment by leerob** [comment]
#### 📝Changed routes:


| [**/404**](https://leerob-git-pr-238.leerob1.now.sh/404) | [**/about**](https://leerob-git-pr-238.leerob1.now.sh/about) |
|:-:|:-:|
|<a href="https://leerob-git-pr-238.leerob1.now.sh/404">Screenshot of /404</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/_1BPnwraoM3waFxcOTMovIutuV0_.png">(view full size)</a> |<a href="https://leerob-git-pr-238.leerob1.now.sh/about">Screenshot of /about</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/exIeYmhrx1AzSCy9VW2Ld_8sNEo_.png">(view full size)</a> |



| [**/blog**](https://leerob-git-pr-238.leerob1.now.sh/blog) | [**/blog/\[slug\]**](https://leerob-git-pr-238.leerob1.now.sh/blog/[slug]) |
|:-:|:-:|
|<a href="https://leerob-git-pr-238.leerob1.now.sh/blog">Screenshot of /blog</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/hnBFF6J1jHiKIsi0bWxBL9xkOQ4_.png">(view full size)</a> |<a href="https://leerob-git-pr-238.leerob1.now.sh/blog/[slug]">Screenshot of /blog/[slug]</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/plY_1P2q38D27GPXrOyPa6hXAmE_.png">(view full size)</a> |



| [**/dashboard**](https://leerob-git-pr-238.leerob1.now.sh/dashboard) | [**/**](https://leerob-git-pr-238.leerob1.now.sh/) |
|:-:|:-:|
|<a href="https://leerob-git-pr-238.leerob1.now.sh/dashboard">Screenshot of /dashboard</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/Hmg67_bXRpSvFpV8UhfT4xckbjc_.png">(view full size)</a> |<a href="https://leerob-git-pr-238.leerob1.now.sh/">Screenshot of /</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/zySXDiv43dx7zBB4YVDxQvUO1GY_.png">(view full size)</a> |



And 3 other routes:
- [**/newsletter**](https://leerob-git-pr-238.leerob1.now.sh/newsletter)
- [**/newsletter/\[slug\]**](https://leerob-git-pr-238.leerob1.now.sh/newsletter/[slug])
- [**/uses**](https://leerob-git-pr-238.leerob1.now.sh/uses)



Commit abb06d3d425859a1cd19c88b87840e2e0c900995 (https://leerob-git-pr-238.leerob1.now.sh).

**Comment by leerob** [comment]
image
Needs to be fixed

**Comment by leerob** [comment]
image

Need to fix wrapping on mobile for snippets. 

I also think mobile is still loading too large of images.

**Comment by leerob** [comment]
Getting close on this massive rewrite. Not sure why I'm losing styles in prod. Need to work through the remaining code TODOs

**Comment by leerob** [comment]
Remaining issues:

- Responsive code blocks on mobile
- Prose styles affecting MDX components

**Comment by leerob** [comment]
Safari shadow on input 
Extra quotes on block quote 
More padding above subscribe component in blog posts and newsletter

**Pull request merged**
