### PR TITLE
Switch to mdx-bundler.

### PR DESCRIPTION
**Pull request by leerob**
- As reported in https://github.com/leerob/leerob.io/issues/317, I was including `MDXProvider` in `_app` unnecessarily. Removing this dropped the First Load JS shared by all from `45.1 kB` to **`35.1 kB`**.
- Running `next build`, `mdx-bundler` is about **40% faster**. Time to generate all blog posts went from `24.5s` to `14.9s`
- Cleaned up all of the dependencies in `package.json` and updated to latest.
- Moved over to rehype plugins and upgraded to their ESM only versions. Now using Next.js 11.1's native ESM support.
- Explored moving from Prism to Highlight.js (and to rehype exclusively), but found the syntax highlighting and token detection much better with Prism.

Side note, but it's kinda nice I don't have to have `@mdx-js/loader`, `@mdx-js/react`, and `@next/mdx` as deps with `mdx-bundler`. Although, I did hit an issue where I made it add `esbuild` as a `devDependency` - but I would think that should be handled by `mdx-bundler`? Not sure.

Also, since `mdx-bundler` is using `xdm`, there's much more strict parsing. I had to remove a few stray characters like `<` from `<1 ms` and `---` from a Markdown front-matter to get it to build successfully.

### CODE REVIEW

**Comment by leerob** [comment]
@peduarte I finally landed here 😆

**Comment by leerob** [comment]
#### 📝Changed routes:


| [**/blog/\[slug\]**](https://leerob-9y83j7hiq-leerob1.vercel.app/blog/[slug]) | [**/newsletter/\[slug\]**](https://leerob-9y83j7hiq-leerob1.vercel.app/newsletter/[slug]) |
|:-:|:-:|
|<a href="https://leerob-9y83j7hiq-leerob1.vercel.app/blog/[slug]">Screenshot of /blog/[slug]</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/4wqYV2fxVIfUawCOdih7SKwv4nag0jqVRevVoPO0MMxKrm5DoEdMfL_5KlKoofgHo-0QNyu_IavwAzr0BhCYlw.png">(view full size)</a> |<a href="https://leerob-9y83j7hiq-leerob1.vercel.app/newsletter/[slug]">Screenshot of /newsletter/[slug]</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/0r-5LuNnEjo-0bK9EimVAUXScWOnH5A1-CC1WIjYebfs6o3dfNjjq7kLQSFmQ1armbhugIHQEJg56EXIQOg0UA.png">(view full size)</a> |



| [**/snippets/\[slug\]**](https://leerob-9y83j7hiq-leerob1.vercel.app/snippets/[slug]) | [**/uses**](https://leerob-9y83j7hiq-leerob1.vercel.app/uses) |
|:-:|:-:|
|<a href="https://leerob-9y83j7hiq-leerob1.vercel.app/snippets/[slug]">Screenshot of /snippets/[slug]</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/OtclyuobnOe64ICgYURMbvqhmOIlwsewEKiDpyDLuateaYqcjJXkqJ168BPZlyy1j2ZcyUE8T-sNs67J0Wiu6g.png">(view full size)</a> |<a href="https://leerob-9y83j7hiq-leerob1.vercel.app/uses">Screenshot of /uses</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/OC7cocjOPWFm6X1LTNK7Gi_KMeQwvZfG84RVZtw5jG0VtPrEtZYKg6DUcxj66lE1168xZyZNfOa7Tcb1qUIvxw.png">(view full size)</a> |







Commit 629c03d0c96b495a1d16ffa14f6a4a6c72a4f6f4 (https://leerob-9y83j7hiq-leerob1.vercel.app).

**Comment by leerob** [comment]
- [ ] Update http://localhost:3000/blog/mdx with latest changes
- [ ] Fix table on Prisma post

**Comment by omaralsoudanii** [comment]
@leerob Nice one!

FYI this is the reasoning behind esbuild as a devDepedency 
https://github.com/kentcdodds/mdx-bundler/pull/62

Also you can add some adjustment to esbuild via `esbuildOptions` specially the target option (I provided example below)

Another enhancement is that if you have some components used within mdx and other sources, you could tell esbuild to not include it in the bundled mdx file (For example if you use Tweets component externally and in mdx files this prevents multiple copies)

This can be done by using `globals` attribute and when you supply mdx components, you add the external one there as well.

See my usage here, hope it's more clear there (and the beginning of the function there is a check, this prevents crashing issues on some browsers using nextjs with mdx-bundler)
https://github.com/omaralsoudanii/mkreg.dev/blob/f067ca07953552e3258d7b659e25bfa4d73f2d69/src/lib/mdx.ts#L80

**Pull request merged**
