### PR TITLE
Remove comma-number package

### PR DESCRIPTION
**Pull request by josiahwiebe**
I was poking around in your site to see your Tailwind implementation (looks great, btw!) and I noticed you could possibly save a few bytes by removing the `comma-number` package and using the built-in [`Intl.NumberFormat`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat) object.

If you're interested, great! Otherwise, feel free to close.

### CODE REVIEW

**Comment by leerob** [comment]
😮 Wow, this is awesome! Great suggestion.

**Comment by leerob** [comment]
I'm still seeing NaN for the newsletter subscribers. Guessing I probably need to add null check there as well?

**Comment by josiahwiebe** [comment]
Hmm, yeah probably. I think we should check for null before attempting to format the number actually, since the formatted number is actually a string.

**Comment by lavgup** [comment]
I personally think it would be better to use `Number(x).toLocaleString()` rather than `Intl.NumberFormat().format(x)` here. Here's my reasoning:

1. It's shorter and more readable.
2. It's supported in all browsers, unlike the latter.
3. The latter should really only be used when dealing with large numbers.

MDN pages:
* [Number.toLocaleString](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString)
* [Intl.NumberFormat.format](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat)

**Pull request closed without merging**
