### PR TITLE
Upgrade to Next 11.

### PR DESCRIPTION
**Pull request by leerob**
🚀

### CODE REVIEW

**Comment by marcorichetta** [comment]
Hi Lee!

First of all, thanks for all the content you publish, it's really helpful.
I saw your code walkthrough about Next and MDX and used it as an exercise to create my blog.

Now I just upgraded to Next 11 and I ran into a similar error as yours.
```bash
yarn run v1.22.10
$ next build
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
info  - Checking validity of types  
node:internal/child_process/serialization:127
    const string = JSONStringify(message) + '\n';
                   ^

TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'name' -> object with constructor 'Object'
    --- property 'parent' closes the circle
    at stringify (<anonymous>)
    at writeChannelMessage (node:internal/child_process/serialization:127:20)
    at process.target._send (node:internal/child_process:822:17)
    at process.target.send (node:internal/child_process:722:19)
    at reportError (/home/marco/Programming/test/personal-site/node_modules/jest-worker/build/workers/processChild.js:87:11)
    at reportClientError (/home/marco/Programming/test/personal-site/node_modules/jest-worker/build/workers/processChild.js:71:10)
node:internal/child_process/serialization:127
    const string = JSONStringify(message) + '\n';
                   ^

# It repeats the same error 4 times

> Build error occurred
Error: Call retries were exceeded
    at ChildProcessWorker.initialize (/home/marco/Programming/test/personal-site/node_modules/jest-worker/build/workers/ChildProcessWorker.js:193:21)
    at ChildProcessWorker._onExit (/home/marco/Programming/test/personal-site/node_modules/jest-worker/build/workers/ChildProcessWorker.js:275:12)
    at ChildProcess.emit (node:events:394:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12) {
  type: 'WorkerError'
}
error Command failed with exit code 1.
```

## `npx next lint` error
On the other hand, `npx next lint` throws the error `Cannot read property 'name' of null`
```tsx
if (isInternalLink) {
    return (
        <Link href={href}>        <---- At this line
            <a {...props} />
        </Link>
    );
}
```
As you can see, this is literally the same logic as yours
https://github.com/leerob/leerob.io/blob/3c66f3bb5b09f95fd972586e76613613781d49e9/components/MDXComponents.js#L19

## Workaround
I think this error seems to be related to eslint because I can run my site with `next dev` **and** `next build --no-lint` without problems.

Also, there's [this SO answer](https://stackoverflow.com/a/27101460/6389248) about JSON not serializing ciruclar objects.
I don't have so much experience the Javascript ecosystem but I hope this info can help solve the issue.

**Comment by maximousblk** [comment]
the `Cannot read property 'name' of null` error is probably an issue with `next lint` ([as discussed in discord](https://discord.com/channels/752553802359505017/752668543891276009/855843933698916362)). but you can temporarily workaround that like so:

```tsx
if (isInternalLink) {
  return (
    <Link href={href}>
      <a {...props} >{props.children}</a> // <==
    </Link>
  );
}
```

**Comment by leerob** [comment]
Nice, thank you both! Will be fixing that upstream 😄

**Comment by marcorichetta** [comment]
Wow, super simple indeed 😂 thanks @maximousblk

**Pull request merged**
