### PR TITLE
Move all content to a CMS (Sanity.io)

### PR DESCRIPTION
**Pull request by leerob**
Since many people fork this repository, I'd like to prevent them from including all of my blog posts and personal information. This PR moves everything from my `data/*` folder to Sanity, which gives me a number of benefits:

- Faster git clone times due to less files and images
- Easier forking for folks looking to use this repo as a template
- Ability to update content without redeploying

This is using the new v3 of Sanity: https://www.sanity.io/blog/sanity-studio-v3-developer-preview

### CODE REVIEW

**Comment by leerob** [comment]
#### 📝 Changed routes:


| [**/blog**](https://leerob-fldkf1gdj-leerob1.vercel.app/blog) | [**/blog/\[slug\]**](https://leerob-fldkf1gdj-leerob1.vercel.app/blog/[slug]) |
|:-:|:-:|
|<a href="https://leerob-fldkf1gdj-leerob1.vercel.app/blog">Screenshot of /blog</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/YGh4dgOnhrBGM-w3tzFptCxNW6Mu1GJJQmF5rbVH0Ljk9iJeMaH4J5XlBBx-UHvraim6zqwhC70aPL4O3c9Agw.png">(view full size)</a> |<a href="https://leerob-fldkf1gdj-leerob1.vercel.app/blog/[slug]">Screenshot of /blog/[slug]</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/K17o9CUeayAdXQhl5-hIwvI9e8d_SWcS4b4LUKj_a3vDoOUYUG9gjKcnxFmzg0mG-gp8VL_-mOTdrxb4zSN3qQ.png">(view full size)</a> |



| [**/feed.xml**](https://leerob-fldkf1gdj-leerob1.vercel.app/feed.xml) | [**/sitemap.xml**](https://leerob-fldkf1gdj-leerob1.vercel.app/sitemap.xml) |
|:-:|:-:|
|<a href="https://leerob-fldkf1gdj-leerob1.vercel.app/feed.xml">Screenshot of /feed.xml</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/kVHSaw5-b8G7hjicGMvYW70Wx37w9_GVuFtMeXT7VNyL_myAwG_DVPCke4IPBqNFeQ1bCzTENXQPG8UJDMWwyQ.png">(view full size)</a> |<a href="https://leerob-fldkf1gdj-leerob1.vercel.app/sitemap.xml">Screenshot of /sitemap.xml</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/DGh1AvX493TP6BR-zFykD2iX_yw6xIQgL1iaDlmtBh-1sBaqSS1F5MLFnxhTsh5UrASiwK-pBc6n1ZMdMNANsQ.png">(view full size)</a> |



| [**/snippets/\[slug\]**](https://leerob-fldkf1gdj-leerob1.vercel.app/snippets/[slug]) | [**/snippets**](https://leerob-fldkf1gdj-leerob1.vercel.app/snippets) |
|:-:|:-:|
|<a href="https://leerob-fldkf1gdj-leerob1.vercel.app/snippets/[slug]">Screenshot of /snippets/[slug]</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/YCvk2Yn_LiXsJo--SWZKzY4dL9NHg-0d1E7QqdWrGxswkfCuHSDqmBHDC9os_yG5c7KzOcvEiOTITYQ3cKgrtA.png">(view full size)</a> |<a href="https://leerob-fldkf1gdj-leerob1.vercel.app/snippets">Screenshot of /snippets</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/aW18yqKmn0DLi7YyTLAn8i7h5ExM6H40uYPfQUIMJb0hYBPxtvQKZdT9au5w95Tyx6WnsK24Mo-Z70t4sB1Cdg.png">(view full size)</a> |



And 4 other routes:
- [**/api/exit-preview**](https://leerob-fldkf1gdj-leerob1.vercel.app/api/exit-preview)
- [**/api/preview**](https://leerob-fldkf1gdj-leerob1.vercel.app/api/preview)
- [**/api/revalidate**](https://leerob-fldkf1gdj-leerob1.vercel.app/api/revalidate)
- [**/uses**](https://leerob-fldkf1gdj-leerob1.vercel.app/uses)



Commit a003d10f0d2800dbbd5fbcc95e14debafc7b75c7 (https://leerob-fldkf1gdj-leerob1.vercel.app).

**Comment by leerob** [comment]
TODO

- Switch back to `pnpm` once https://github.com/sanity-io/sanity/issues/3336 is resolved.
- Decide if I want to migrate the rest of the images included in `public` to sanity (images inlined in blog posts)

**Comment by leerob** [comment]
Think I'm gonna fix Preview Mode in a follow-up PR. Worth merging now!

**Comment by XahidEx** [comment]
I also need to need how to do all these. 🥲

**Comment by leerob** [comment]
There's more benefits that just that, namely that I can update content without redeploying 😄

**Comment by trm217** [comment]
@leerob Why did you disable the usage of preact in production?

**Comment by leerob** [comment]
There's currently a bug it seems where the `meta` tags in the `head` like title and description weren't working.

**Comment by Music47ell** [comment]
> There's currently a bug it seems where the `meta` tags in the `head` like title and description weren't working.

I've been struggling with this issue for the past week. I undid all the changes I made, tried different versions of packages I'm using. Nothing worked. 

Just now, I decided to get rid of preact because I noticed you're not using it and the meta tags in my site started to work again. 

Little bit of searching in this repository, and I just stumbled upon this 🤦‍♂️😂

**Pull request merged**
