### PR TITLE
Switch to server-side analytics through Supabase.

### PR DESCRIPTION
**Pull request by leerob**
Less client-side scripts! Less JavaScript loaded! 🙌 Shout out to [Middleware](https://nextjs.org/docs/middleware) and [Supabase](https://supabase.io/).

image

### CODE REVIEW

**Comment by cupboard319** [comment]
@leerob This looks really great. I tried to implement the same. How to finish the setup after creating the project in Supabase? I've added these two APIs in `.env` file 
image

**Comment by aktschge** [comment]
Hi @leerob. It's been really insightful going through your repository while I tried to learn more about the `contentlayer` module! Thanks for having it open source!

However, I just saw your server-side implementation of analytics and am curious whether it is possible to disable the counting of prefetched links? Right now prefetched links also count towards `views`. But the goal would be to count them only when a user clicks and lands on a given page. Would be happy to discuss.

**Comment by leerob** [comment]
Hey! Glad you've found it helpful 😄 

Middleware doesn't run on hover, since it's executing code server-side 👍

**Comment by aktschge** [comment]
Hi again! Sorry for bothering you so much, but I am just curious. So I played around a bit with a fresh `Next` project and used the `Link` component provided by `next/link` where I set `prefetch={false}`.

I then followed your implementation for `_middleware` and found out that `_middleware` also does run on hover. According to your comment I guess that this is not the expected behavior then?

server-analytics-tracking-hover

**Side Note:** It also tracks analytics when `prefetch={true}` though.

**Comment by vnglst** [comment]
Hi all! I also gave this a try because it looks to seductively simple. And it seems to work perfectly, until you hit production. There I noticed that NextJS is prefetching all the currently visible links. This is great for performance, but not so good if you want to track analytics.

Do you know if there's a way to differentiate between requests made as a prefetch and regular user page loads? Does Next add anything to prefetch request that we could use to filter out those requests. Otherwise I think we're stuck with some kind of client side/JS implementation.

**Comment by vnglst** [comment]
A quick update on analytics using Supabase. On my personal website I've moved the API call to the client in this [PR](https://github.com/vnglst/koenvangilst.nl/pull/92). 

It's now very similar to your implementation with Planetscale @leerob. But I think this should work pretty well. (not as cool as a completely server side implementation though).

**Comment by vnglst** [comment]
Quick update: @gbibeaul found a way to filter out prefetches using the NextJS header `x-middleware-preflight`. You can see his example here: https://github.com/vercel/examples/blob/1a8c5e1854a01437f2f9bb7a5bbbea1da63ba4d7/edge-functions/analytics/pages/_middleware.ts#L39

**Comment by leerob** [comment]
Closing for now 😄

**Pull request closed without merging**
