### PR TITLE
Remove unused dependency `swr`

### PR DESCRIPTION
**Pull request by vinaykulk621**

### CODE REVIEW

**Comment by alex289** [comment]
You need to update the lockfile by running `pnpm install`

**Comment by vinaykulk621** [comment]
Thanks, updated.

**Review by leerob — APPROVED** [review]

**Comment by leerob** [comment]
CleanShot 2023-07-18 at 19 47 23@2x

Hmm, still seems off.

**Comment by vinaykulk621** [comment]
I don't seem to find the issue here.
I have reverted previous commit on updating the `package-lock.yaml` and 
run `pnpm install` and updated the `package-lock.yaml` in my recent commit.

**Comment by vinaykulk621** [comment]
@leerob 
Followed this issue [https://github.com/vercel/vercel/issues/8272](https://github.com/vercel/vercel/issues/8272)
Coments on this issue said run `pnpm install --no-frozen-lockfile`.
I am using github codespace.

```
node -v  -->v20.3.0

pnpm -v -->8.6.2
```

**Pull request closed without merging**
